// Code generated by hertz generator.

package github_hook

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _releasehookMw() []app.HandlerFunc {
	// your code...
	return nil
}
