// Code generated by hertz generator.

package main

import (
	"context"
	"github.com/joho/godotenv"
	"github.com/li1553770945/openmcp-discord-bot/cogs"
	"github.com/li1553770945/openmcp-discord-bot/httpserver"
	configInfra "github.com/li1553770945/openmcp-discord-bot/infra/config"
	"github.com/li1553770945/openmcp-discord-bot/logger"
	"go.uber.org/zap"
	"os"
	"os/signal"
	"sync"
	"syscall"
)

var GlobalWg *sync.WaitGroup
var GlobalStopChan chan bool

func main() {
	defer func() {
		if err := recover(); err != nil {
			zap.S().Errorf("主函数发生错误导致退出：%v", err)
		}
	}()

	logger.InitLogger("logs")
	//从.env加载环境变量
	err := godotenv.Load()
	if err != nil {
		panic("无法获取.env环境变量")
	}

	//加载配置
	err = configInfra.InitConfig("config", "config", "yaml")
	if err != nil {
		panic("加载配置文件失败")
	}
	zap.S().Info("配置加载成功")

	GlobalWg = new(sync.WaitGroup)
	ctx, cancel := context.WithCancel(context.Background())

	//启动http服务器
	httpserver.StartHttpServer(ctx, GlobalWg)

	cfg := configInfra.GetConfig()
	cogs.InitGlobalBot(cfg.Discord.Token, ctx, GlobalWg)

	zap.S().Info("机器人服务与http服务均开始运行，按下CTRL-C退出")
	sc := make(chan os.Signal, 1)
	signal.Notify(sc, syscall.SIGINT, syscall.SIGTERM, os.Interrupt)
	<-sc

	zap.S().Infof("收到退出信号，正在执行优雅退出")

	cancel()

	GlobalWg.Wait()

	zap.S().Infof("已正常退出")
}
