// Code generated by hertz generator.

package github_hook

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ReleaseHook .
// @router /github-release [GET]
func ReleaseHook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(string)

	c.JSON(consts.StatusOK, resp)
}
